//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMeasurement.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageDic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageDic() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineMeasurement.Resources.LanguageDic", typeof(LanguageDic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 却不存 的本地化字符串。
        /// </summary>
        internal static string but_not_exist {
            get {
                return ResourceManager.GetString("but_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机 的本地化字符串。
        /// </summary>
        internal static string cam {
            get {
                return ResourceManager.GetString("cam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照异常 的本地化字符串。
        /// </summary>
        internal static string cam_error {
            get {
                return ResourceManager.GetString("cam_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机打开失败 的本地化字符串。
        /// </summary>
        internal static string cam_open_fail {
            get {
                return ResourceManager.GetString("cam_open_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机打开成功 的本地化字符串。
        /// </summary>
        internal static string cam_open_success {
            get {
                return ResourceManager.GetString("cam_open_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照0失败 的本地化字符串。
        /// </summary>
        internal static string cam0_fail {
            get {
                return ResourceManager.GetString("cam0_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照1失败 的本地化字符串。
        /// </summary>
        internal static string cam1_fail {
            get {
                return ResourceManager.GetString("cam1_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车号 的本地化字符串。
        /// </summary>
        internal static string car_no {
            get {
                return ResourceManager.GetString("car_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连番信息读取失败 的本地化字符串。
        /// </summary>
        internal static string car_no_info_read_fail {
            get {
                return ResourceManager.GetString("car_no_info_read_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连番号 的本地化字符串。
        /// </summary>
        internal static string car_no2 {
            get {
                return ResourceManager.GetString("car_no2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换语言成功 的本地化字符串。
        /// </summary>
        internal static string change_language_success {
            get {
                return ResourceManager.GetString("change_language_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测结果 的本地化字符串。
        /// </summary>
        internal static string check_result {
            get {
                return ResourceManager.GetString("check_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量结果可读写入失败 的本地化字符串。
        /// </summary>
        internal static string check_result_readable_write_fail {
            get {
                return ResourceManager.GetString("check_result_readable_write_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量结果写入失败 的本地化字符串。
        /// </summary>
        internal static string check_result_write_fail {
            get {
                return ResourceManager.GetString("check_result_write_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭成功 的本地化字符串。
        /// </summary>
        internal static string close_success {
            get {
                return ResourceManager.GetString("close_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新连接成功 的本地化字符串。
        /// </summary>
        internal static string connect_again_success {
            get {
                return ResourceManager.GetString("connect_again_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败 的本地化字符串。
        /// </summary>
        internal static string connection_failed {
            get {
                return ResourceManager.GetString("connection_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接成功 的本地化字符串。
        /// </summary>
        internal static string connection_successful {
            get {
                return ResourceManager.GetString("connection_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在非法字符 的本地化字符串。
        /// </summary>
        internal static string contains_illegal_characters {
            get {
                return ResourceManager.GetString("contains_illegal_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 坐标计算完成 的本地化字符串。
        /// </summary>
        internal static string Coordinate_calculation_completed {
            get {
                return ResourceManager.GetString("Coordinate_calculation_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制至全部车型 的本地化字符串。
        /// </summary>
        internal static string copy_to_all_model {
            get {
                return ResourceManager.GetString("copy_to_all_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能重复添加 的本地化字符串。
        /// </summary>
        internal static string could_not_repect_add {
            get {
                return ResourceManager.GetString("could_not_repect_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建文件夹 的本地化字符串。
        /// </summary>
        internal static string create_dir {
            get {
                return ResourceManager.GetString("create_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其中创建目录耗时 的本地化字符串。
        /// </summary>
        internal static string create_dir_use_time {
            get {
                return ResourceManager.GetString("create_dir_use_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接测试失败 的本地化字符串。
        /// </summary>
        internal static string database_connect_fail {
            get {
                return ResourceManager.GetString("database_connect_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接测试成功 的本地化字符串。
        /// </summary>
        internal static string database_connect_success {
            get {
                return ResourceManager.GetString("database_connect_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库写入异常 的本地化字符串。
        /// </summary>
        internal static string database_write_error {
            get {
                return ResourceManager.GetString("database_write_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 棱 的本地化字符串。
        /// </summary>
        internal static string edge {
            get {
                return ResourceManager.GetString("edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 末点 的本地化字符串。
        /// </summary>
        internal static string end_point {
            get {
                return ResourceManager.GetString("end_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在 的本地化字符串。
        /// </summary>
        internal static string exist {
            get {
                return ResourceManager.GetString("exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string fail {
            get {
                return ResourceManager.GetString("fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取位号失败 的本地化字符串。
        /// </summary>
        internal static string fail_get_point_NO {
            get {
                return ResourceManager.GetString("fail_get_point_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件格式异常 的本地化字符串。
        /// </summary>
        internal static string file_format_error {
            get {
                return ResourceManager.GetString("file_format_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在 的本地化字符串。
        /// </summary>
        internal static string file_not_exist {
            get {
                return ResourceManager.GetString("file_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 张 的本地化字符串。
        /// </summary>
        internal static string fix {
            get {
                return ResourceManager.GetString("fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式不正确 的本地化字符串。
        /// </summary>
        internal static string format_error {
            get {
                return ResourceManager.GetString("format_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 孔 的本地化字符串。
        /// </summary>
        internal static string hole {
            get {
                return ResourceManager.GetString("hole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存图进内存完成 的本地化字符串。
        /// </summary>
        internal static string Image_storage_into_memory_completed {
            get {
                return ResourceManager.GetString("Image_storage_into_memory_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴区域大小不一致 的本地化字符串。
        /// </summary>
        internal static string inconsistent_size_of_pasting_area {
            get {
                return ResourceManager.GetString("inconsistent_size_of_pasting_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式有误，转换失败 的本地化字符串。
        /// </summary>
        internal static string Incorrect_format_conversion_failed {
            get {
                return ResourceManager.GetString("Incorrect_format_conversion_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否保存参数 的本地化字符串。
        /// </summary>
        internal static string is_save_para {
            get {
                return ResourceManager.GetString("is_save_para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L拍照完成写入失败 的本地化字符串。
        /// </summary>
        internal static string L_photo_finish_write_fail {
            get {
                return ResourceManager.GetString("L_photo_finish_write_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L机器人任务被取消 的本地化字符串。
        /// </summary>
        internal static string L_robot_cancle {
            get {
                return ResourceManager.GetString("L_robot_cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L机器人任务异常 的本地化字符串。
        /// </summary>
        internal static string L_robot_error {
            get {
                return ResourceManager.GetString("L_robot_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L机器人任务完成 的本地化字符串。
        /// </summary>
        internal static string L_robot_finish {
            get {
                return ResourceManager.GetString("L_robot_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激光坐标超出标定范围 的本地化字符串。
        /// </summary>
        internal static string Laser_coordinates_exceed_the_calibration_range {
            get {
                return ResourceManager.GetString("Laser_coordinates_exceed_the_calibration_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 许可错误！ 的本地化字符串。
        /// </summary>
        internal static string License_error {
            get {
                return ResourceManager.GetString("License_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配异常 的本地化字符串。
        /// </summary>
        internal static string match_error {
            get {
                return ResourceManager.GetString("match_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匹配失败 的本地化字符串。
        /// </summary>
        internal static string Match_fail {
            get {
                return ResourceManager.GetString("Match_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大化 的本地化字符串。
        /// </summary>
        internal static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车型 的本地化字符串。
        /// </summary>
        internal static string model_no {
            get {
                return ResourceManager.GetString("model_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车型代码读取失败 的本地化字符串。
        /// </summary>
        internal static string model_no_code_read_fail {
            get {
                return ResourceManager.GetString("model_no_code_read_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车型码写入失败 的本地化字符串。
        /// </summary>
        internal static string model_no_code_write_fail {
            get {
                return ResourceManager.GetString("model_no_code_write_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车型号 的本地化字符串。
        /// </summary>
        internal static string model_no2 {
            get {
                return ResourceManager.GetString("model_no2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车型参数不存在 的本地化字符串。
        /// </summary>
        internal static string model_para_not_exist {
            get {
                return ResourceManager.GetString("model_para_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称已存在 的本地化字符串。
        /// </summary>
        internal static string name_already_exist {
            get {
                return ResourceManager.GetString("name_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 坐标校准需要输入全部数据 的本地化字符串。
        /// </summary>
        internal static string need_input_all_value {
            get {
                return ResourceManager.GetString("need_input_all_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要输入数字名称 的本地化字符串。
        /// </summary>
        internal static string need_to_input_num {
            get {
                return ResourceManager.GetString("need_to_input_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机未做标定 的本地化字符串。
        /// </summary>
        internal static string no_cam_calib {
            get {
                return ResourceManager.GetString("no_cam_calib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未做模板 的本地化字符串。
        /// </summary>
        internal static string no_model {
            get {
                return ResourceManager.GetString("no_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在 的本地化字符串。
        /// </summary>
        internal static string not_exist {
            get {
                return ResourceManager.GetString("not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未输入名称 的本地化字符串。
        /// </summary>
        internal static string not_input_name {
            get {
                return ResourceManager.GetString("not_input_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选择修改项 的本地化字符串。
        /// </summary>
        internal static string not_select_change_item {
            get {
                return ResourceManager.GetString("not_select_change_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选择删除项 的本地化字符串。
        /// </summary>
        internal static string not_select_delete_item {
            get {
                return ResourceManager.GetString("not_select_delete_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非值类型 的本地化字符串。
        /// </summary>
        internal static string not_value {
            get {
                return ResourceManager.GetString("not_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线计测系统 的本地化字符串。
        /// </summary>
        internal static string Online_Det {
            get {
                return ResourceManager.GetString("Online_Det", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出准备好信号 的本地化字符串。
        /// </summary>
        internal static string output_ready_signal {
            get {
                return ResourceManager.GetString("output_ready_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 托盘号 的本地化字符串。
        /// </summary>
        internal static string pallet_no {
            get {
                return ResourceManager.GetString("pallet_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 托盘号读取失败 的本地化字符串。
        /// </summary>
        internal static string pallet_no_read_fail {
            get {
                return ResourceManager.GetString("pallet_no_read_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数已加载 的本地化字符串。
        /// </summary>
        internal static string para_already_load {
            get {
                return ResourceManager.GetString("para_already_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未做参数 的本地化字符串。
        /// </summary>
        internal static string para_has_not_made {
            get {
                return ResourceManager.GetString("para_has_not_made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数加载失败 的本地化字符串。
        /// </summary>
        internal static string para_load_fail {
            get {
                return ResourceManager.GetString("para_load_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数加载成功 的本地化字符串。
        /// </summary>
        internal static string para_load_success {
            get {
                return ResourceManager.GetString("para_load_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数读取失败 的本地化字符串。
        /// </summary>
        internal static string Para_read_fail {
            get {
                return ResourceManager.GetString("Para_read_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照姿态到位信号读取失败 的本地化字符串。
        /// </summary>
        internal static string Photo_posture_in_place_signal_reading_failed {
            get {
                return ResourceManager.GetString("Photo_posture_in_place_signal_reading_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 像素 的本地化字符串。
        /// </summary>
        internal static string pix {
            get {
                return ResourceManager.GetString("pix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 张图在内存中未存进硬盘 的本地化字符串。
        /// </summary>
        internal static string pix_not_save_to_hard_disk_in_memory {
            get {
                return ResourceManager.GetString("pix_not_save_to_hard_disk_in_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请重新填写 的本地化字符串。
        /// </summary>
        internal static string please_fill_it_out_again {
            get {
                return ResourceManager.GetString("please_fill_it_out_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位号读取失败 的本地化字符串。
        /// </summary>
        internal static string Point_number_reading_failed {
            get {
                return ResourceManager.GetString("Point_number_reading_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位号反馈写入失败 的本地化字符串。
        /// </summary>
        internal static string Point_number_writing_failed {
            get {
                return ResourceManager.GetString("Point_number_writing_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程结束 的本地化字符串。
        /// </summary>
        internal static string Process_ended {
            get {
                return ResourceManager.GetString("Process_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品ID已存在 的本地化字符串。
        /// </summary>
        internal static string product_id_already_exist {
            get {
                return ResourceManager.GetString("product_id_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品ID不能为空 的本地化字符串。
        /// </summary>
        internal static string product_id_could_not_null {
            get {
                return ResourceManager.GetString("product_id_could_not_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品ID格式不正确 的本地化字符串。
        /// </summary>
        internal static string product_id_format_is_not_correct {
            get {
                return ResourceManager.GetString("product_id_format_is_not_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称已存在 的本地化字符串。
        /// </summary>
        internal static string product_name_already_exist {
            get {
                return ResourceManager.GetString("product_name_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称不能包含字符 的本地化字符串。
        /// </summary>
        internal static string product_name_could_contine_char {
            get {
                return ResourceManager.GetString("product_name_could_contine_char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称不能为空 的本地化字符串。
        /// </summary>
        internal static string product_name_could_not_null {
            get {
                return ResourceManager.GetString("product_name_could_not_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R拍照完成写入失败 的本地化字符串。
        /// </summary>
        internal static string R_photo_finish_write_fail {
            get {
                return ResourceManager.GetString("R_photo_finish_write_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R机器人任务被取消 的本地化字符串。
        /// </summary>
        internal static string R_robot_cancle {
            get {
                return ResourceManager.GetString("R_robot_cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R机器人任务异常 的本地化字符串。
        /// </summary>
        internal static string R_robot_error {
            get {
                return ResourceManager.GetString("R_robot_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R机器人任务完成 的本地化字符串。
        /// </summary>
        internal static string R_robot_finish {
            get {
                return ResourceManager.GetString("R_robot_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取机器人位姿失败 的本地化字符串。
        /// </summary>
        internal static string Read_pose_fail {
            get {
                return ResourceManager.GetString("Read_pose_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已读信号读取失败 的本地化字符串。
        /// </summary>
        internal static string read_signal_read_fail {
            get {
                return ResourceManager.GetString("read_signal_read_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备好写入失败 的本地化字符串。
        /// </summary>
        internal static string ready_write_fail {
            get {
                return ResourceManager.GetString("ready_write_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重建坐标异常 的本地化字符串。
        /// </summary>
        internal static string reconstruct_coordinates_error {
            get {
                return ResourceManager.GetString("reconstruct_coordinates_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余 的本地化字符串。
        /// </summary>
        internal static string remain {
            get {
                return ResourceManager.GetString("remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复 的本地化字符串。
        /// </summary>
        internal static string repeat {
            get {
                return ResourceManager.GetString("repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试中 的本地化字符串。
        /// </summary>
        internal static string repect_again {
            get {
                return ResourceManager.GetString("repect_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到点位 的本地化字符串。
        /// </summary>
        internal static string reserve_end_point {
            get {
                return ResourceManager.GetString("reserve_end_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到已读信号 的本地化字符串。
        /// </summary>
        internal static string reserve_read_signal {
            get {
                return ResourceManager.GetString("reserve_read_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到重置流程信号 的本地化字符串。
        /// </summary>
        internal static string reserve_reset_signal {
            get {
                return ResourceManager.GetString("reserve_reset_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到开始信号 的本地化字符串。
        /// </summary>
        internal static string reserve_start_signal {
            get {
                return ResourceManager.GetString("reserve_start_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到拍照姿态到位信号 的本地化字符串。
        /// </summary>
        internal static string reserve_the_signal_that_the_camera_posture_is_in_place {
            get {
                return ResourceManager.GetString("reserve_the_signal_that_the_camera_posture_is_in_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置流程信号读取失败 的本地化字符串。
        /// </summary>
        internal static string reset_signal_read_fail {
            get {
                return ResourceManager.GetString("reset_signal_read_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还原 的本地化字符串。
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果写入失败 的本地化字符串。
        /// </summary>
        internal static string result_write_fail {
            get {
                return ResourceManager.GetString("result_write_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器人温漂标定失败 的本地化字符串。
        /// </summary>
        internal static string robot_tempareture_calib_fail {
            get {
                return ResourceManager.GetString("robot_tempareture_calib_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器人温漂标定成功 的本地化字符串。
        /// </summary>
        internal static string robot_tempareture_calib_success {
            get {
                return ResourceManager.GetString("robot_tempareture_calib_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根节点 的本地化字符串。
        /// </summary>
        internal static string root_node {
            get {
                return ResourceManager.GetString("root_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空运行信号 的本地化字符串。
        /// </summary>
        internal static string run_empty_signal {
            get {
                return ResourceManager.GetString("run_empty_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空运行信号读取失败 的本地化字符串。
        /// </summary>
        internal static string run_empty_signal_read_fail {
            get {
                return ResourceManager.GetString("run_empty_signal_read_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行中写入失败 的本地化字符串。
        /// </summary>
        internal static string running_write_fail {
            get {
                return ResourceManager.GetString("running_write_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        internal static string save_fail {
            get {
                return ResourceManager.GetString("save_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存图异常 的本地化字符串。
        /// </summary>
        internal static string save_img_error {
            get {
                return ResourceManager.GetString("save_img_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存图完成 的本地化字符串。
        /// </summary>
        internal static string save_img_finish {
            get {
                return ResourceManager.GetString("save_img_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存图异常 的本地化字符串。
        /// </summary>
        internal static string save_pic_error {
            get {
                return ResourceManager.GetString("save_pic_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存图耗时 的本地化字符串。
        /// </summary>
        internal static string save_pic_use_time {
            get {
                return ResourceManager.GetString("save_pic_use_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string save_success {
            get {
                return ResourceManager.GetString("save_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口已经打开 的本地化字符串。
        /// </summary>
        internal static string Serial_port_already_opened {
            get {
                return ResourceManager.GetString("Serial_port_already_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口打开失败 的本地化字符串。
        /// </summary>
        internal static string Serial_port_failly_opened {
            get {
                return ResourceManager.GetString("Serial_port_failly_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口发送异常 的本地化字符串。
        /// </summary>
        internal static string Serial_port_sending_exception {
            get {
                return ResourceManager.GetString("Serial_port_sending_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口打开成功 的本地化字符串。
        /// </summary>
        internal static string Serial_port_successfully_opened {
            get {
                return ResourceManager.GetString("Serial_port_successfully_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曝光0设置失败 的本地化字符串。
        /// </summary>
        internal static string set_cam0_export_fail {
            get {
                return ResourceManager.GetString("set_cam0_export_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曝光1设置失败 的本地化字符串。
        /// </summary>
        internal static string set_cam1_export_fail {
            get {
                return ResourceManager.GetString("set_cam1_export_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信号重新读取成功 的本地化字符串。
        /// </summary>
        internal static string signal_read_again_success {
            get {
                return ResourceManager.GetString("signal_read_again_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信号读取失败 的本地化字符串。
        /// </summary>
        internal static string signal_read_fail {
            get {
                return ResourceManager.GetString("signal_read_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信号写入失败 的本地化字符串。
        /// </summary>
        internal static string signal_rewrite_fail {
            get {
                return ResourceManager.GetString("signal_rewrite_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信号重新写入成功 的本地化字符串。
        /// </summary>
        internal static string signal_rewrite_success {
            get {
                return ResourceManager.GetString("signal_rewrite_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳过本次存图 的本地化字符串。
        /// </summary>
        internal static string skip_this_save_image {
            get {
                return ResourceManager.GetString("skip_this_save_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件已设置禁止多开 的本地化字符串。
        /// </summary>
        internal static string software_could_open_mul {
            get {
                return ResourceManager.GetString("software_could_open_mul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件正在运行中 的本地化字符串。
        /// </summary>
        internal static string software_is_running {
            get {
                return ResourceManager.GetString("software_is_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始计算坐标 的本地化字符串。
        /// </summary>
        internal static string Start_calculating_coordinates {
            get {
                return ResourceManager.GetString("Start_calculating_coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始存图 的本地化字符串。
        /// </summary>
        internal static string start_img {
            get {
                return ResourceManager.GetString("start_img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始信号读取失败 的本地化字符串。
        /// </summary>
        internal static string start_signal_read_fail {
            get {
                return ResourceManager.GetString("start_signal_read_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始存图进内存 的本地化字符串。
        /// </summary>
        internal static string Start_storing_images_into_memory {
            get {
                return ResourceManager.GetString("Start_storing_images_into_memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功获取点位号 的本地化字符串。
        /// </summary>
        internal static string success_get_point_NO {
            get {
                return ResourceManager.GetString("success_get_point_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定退出 的本地化字符串。
        /// </summary>
        internal static string sure_exist {
            get {
                return ResourceManager.GetString("sure_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否确定跳过开始信号 的本地化字符串。
        /// </summary>
        internal static string sure_skip_start_signal {
            get {
                return ResourceManager.GetString("sure_skip_start_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照异常 的本地化字符串。
        /// </summary>
        internal static string take_photo_error {
            get {
                return ResourceManager.GetString("take_photo_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照结束 的本地化字符串。
        /// </summary>
        internal static string take_photo_finish {
            get {
                return ResourceManager.GetString("take_photo_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照完成写入 的本地化字符串。
        /// </summary>
        internal static string take_photo_finish_write {
            get {
                return ResourceManager.GetString("take_photo_finish_write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照完成写入失败 的本地化字符串。
        /// </summary>
        internal static string take_photo_finish_write_fail {
            get {
                return ResourceManager.GetString("take_photo_finish_write_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建坐标点数量小于 的本地化字符串。
        /// </summary>
        internal static string The_number_of_coordinate_points_is_less_than {
            get {
                return ResourceManager.GetString("The_number_of_coordinate_points_is_less_than", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径存在非法字符 的本地化字符串。
        /// </summary>
        internal static string the_path_contains_illegal_characters {
            get {
                return ResourceManager.GetString("the_path_contains_illegal_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照距离超出标定范围 的本地化字符串。
        /// </summary>
        internal static string The_photography_distance_exceeds_the_calibration_range {
            get {
                return ResourceManager.GetString("The_photography_distance_exceeds_the_calibration_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入值与读取值不一致 的本地化字符串。
        /// </summary>
        internal static string The_written_value_is_inconsistent_with_the_read_value {
            get {
                return ResourceManager.GetString("The_written_value_is_inconsistent_with_the_read_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string tip {
            get {
                return ResourceManager.GetString("tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入长度过长 的本地化字符串。
        /// </summary>
        internal static string too_long {
            get {
                return ResourceManager.GetString("too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨迹末点读取失败 的本地化字符串。
        /// </summary>
        internal static string Trajectory_endpoint_reading_failed {
            get {
                return ResourceManager.GetString("Trajectory_endpoint_reading_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 槽 的本地化字符串。
        /// </summary>
        internal static string trough {
            get {
                return ResourceManager.GetString("trough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法重建坐标 的本地化字符串。
        /// </summary>
        internal static string Unable_to_reconstruct_coordinates {
            get {
                return ResourceManager.GetString("Unable_to_reconstruct_coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程耗时 的本地化字符串。
        /// </summary>
        internal static string use_time {
            get {
                return ResourceManager.GetString("use_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 耗时 的本地化字符串。
        /// </summary>
        internal static string use_time2 {
            get {
                return ResourceManager.GetString("use_time2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户执行了停止 的本地化字符串。
        /// </summary>
        internal static string user_stop {
            get {
                return ResourceManager.GetString("user_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车架号读取失败 的本地化字符串。
        /// </summary>
        internal static string vin_read_fail {
            get {
                return ResourceManager.GetString("vin_read_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车架号 的本地化字符串。
        /// </summary>
        internal static string vin2 {
            get {
                return ResourceManager.GetString("vin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待 的本地化字符串。
        /// </summary>
        internal static string wait {
            get {
                return ResourceManager.GetString("wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待点位号发送 的本地化字符串。
        /// </summary>
        internal static string wait_for_point_NO {
            get {
                return ResourceManager.GetString("wait_for_point_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待已读信号 的本地化字符串。
        /// </summary>
        internal static string wait_for_read_signal {
            get {
                return ResourceManager.GetString("wait_for_read_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待机器人任务完成 的本地化字符串。
        /// </summary>
        internal static string wait_for_robot_finish {
            get {
                return ResourceManager.GetString("wait_for_robot_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待开始信号 的本地化字符串。
        /// </summary>
        internal static string wait_start_signal {
            get {
                return ResourceManager.GetString("wait_start_signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待拍照姿态到位信号 的本地化字符串。
        /// </summary>
        internal static string Waiting_for_the_signal_that_the_camera_posture_is_in_place {
            get {
                return ResourceManager.GetString("Waiting_for_the_signal_that_the_camera_posture_is_in_place", resourceCulture);
            }
        }
    }
}
